services:
    sonata.admin.parts:
        class: App\Admin\PartAdmin
        arguments: [~, App\Entity\Part, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Parts }
        public: true

    sonata.admin.part_types:
        class: App\Admin\PartTypeAdmin
        arguments: [~, App\Entity\PartType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: PartTypes }
        public: true