<?php
/**
 * Created by PhpStorm.
 * User: paktus-lnx
 * Date: 01.05.18
 * Time: 16:27
 */

namespace App\Admin;


use App\Service\ImgUrService;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;

class Admin extends AbstractAdmin
{
    protected $imgUr_fields = [];

    public function __construct(string $code, string $class, string $baseControllerName)
    {
        parent::__construct($code, $class, $baseControllerName);
    }


    public function preUpdate($object)
    {
        $this->uploadToImgur($object, $this->request);
        parent::preUpdate($object); // TODO: Change the autogenerated stub
    }

    public function prePersist($object)
    {
        $this->uploadToImgur($object, $this->request);
        parent::prePersist($object); // TODO: Change the autogenerated stub
    }

    private function uploadToImgur($object, Request $request)
    {
        $imgService = $this->getConfigurationPool()->getContainer()->get(ImgUrService::class);
        foreach ($this->imgUr_fields as $field) {
            $set = 'set' . ucfirst($field);
            $get = 'get' . ucfirst($field);
            /** @var UploadedFile $file */
            $file = $request->files->get($field . '_file'    );
            if (!is_null($file)) {
                if($object->$get()){
                    $imgService->deleteImage($object->$get($field)['deletehash']);
                }
                $object->$set($imgService->uploadImage($file->getPathname()));
            }
        }
    }

    public function preRemove($object)
    {
        $this->removeImages($object);
        parent::preRemove($object); // TODO: Change the autogenerated stub
    }

    private function removeImages($object)
    {
        $imgService = $this->getConfigurationPool()->getContainer()->get(ImgUrService::class);
        foreach ($this->imgUr_fields as $field) {
            $get = 'get' . ucfirst($field);
            $set = 'set' . ucfirst($field);
            if ($object->$get($field)) {
                $imgService->deleteImage($object->$get($field)['deletehash']);
            }
        }
    }

    protected function configureListFields(ListMapper $list)
    {
        $list->add('_action', null, [
            'actions' => [
                'edit' => [],
                'delete' => [],
            ]
        ]);
        parent::configureListFields($list); // TODO: Change the autogenerated stub
    }


}